DATA PRE-PROCESSING

In [2]:
import pandas as pd
file_path = '../data/raw/kidney_disease.csv'
df = pd.read_csv(file_path)
pd.set_option('display.max_columns', None)
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    str
 7   pc              335 non-null    str
 8   pcc             396 non-null    str
 9   ba              396 non-null    str
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    str
 17  wc              295 non-null    str
 18  rc              270 non-null    str
 19  htn             398 non-null    str
 20  dm              398 non-null    str
 21  cad             398 non-null    str
 22  appet           399 non-null    str
 23  pe              399 non-null    str
 24  ane             399 non-null    str
 25  classification  400 non-null    str
dtypes: float64(11), int64(1), str(14)
memory usage: 81.4 KB

In [6]:
df['pcv'] = pd.to_numeric(df['pcv'], errors='coerce')
df['wc'] = pd.to_numeric(df['wc'], errors='coerce')
df['rc'] = pd.to_numeric(df['rc'], errors='coerce')

df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                71
wc                106
rc                131
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [7]:
#separating columns into numbers and catagories
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
cat_cols = df.select_dtypes(include=['object', 'str']).columns

#filling numerical missing cells with medians
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

#filling categorical missing cells with modes
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum().sum()

0

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cat_cols = df. select_dtypes(include=['object', 'str']).columns

for cols in cat_cols:
    df[cols] = le.fit_transform(df[col])

df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,0,0,0,0,121.0,36.0,1.2,138.0,4.4,15.4,44.0,7800.0,5.2,0,0,0,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,0,0,0,0,121.0,18.0,0.8,138.0,4.4,11.3,38.0,6000.0,4.8,0,0,0,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,0,0,0,0,423.0,53.0,1.8,138.0,4.4,9.6,31.0,7500.0,4.8,0,0,0,0,0,0,0
3,3,48.0,70.0,1.005,4.0,0.0,0,0,0,0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9,0,0,0,0,0,0,0
4,4,51.0,80.0,1.010,2.0,0.0,0,0,0,0,106.0,26.0,1.4,138.0,4.4,11.6,35.0,7300.0,4.6,0,0,0,0,0,0,0

In [9]:
df.to_csv('../data/processed/cleaned_kidney_data.csv', index=False)

print("Sample purified and stored in data/processed!")

Sample purified and stored in data/processed!